version: "3"
services:
    hungrypoints_node:
        build: 
            context: ./backend/
            dockerfile: Dockerfile
        ports:
            - 3333:3333
        container_name: node
        depends_on:
        environment:
            - REDIS_HOSTNAME=hungrypoints_redis
            - MONGO_HOSTNAME=hungrypoints_mongodb
            - REACT_HOSTNAME=hungrypoints_react

    hungrypoints_react:
        build: 
            context: ./frontend/
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        container_name: react
        depends_on:
            - hungrypoints_node